package com.lsfb.cysj.app;

public class MyUrl {
	public static String StringVerificationCode = "http://cysj.coolmoban.com/Register/members/act/membercheck";// 验证码发送
	public static String Stringzhuce = "http://cysj.coolmoban.com/Register/members/act/register";// 注册
	public static String StringSgin = "http://cysj.coolmoban.com/Register/members/act/memdl";// 登录
	public static String StringEditdata = "http://cysj.coolmoban.com/Register/members/act/mempersonalxs";// 编辑资料
	public static String StringMeditation = "http://cysj.coolmoban.com/Friends/merits/act/meritslist";// 禅修
	public static String meritsadd = "http://cysj.coolmoban.com/Friends/merits/act/meritsadd";// 家庭禅修添加
	public static String region = "http://cysj.coolmoban.com/Common/commons/act/region";// 地区选择
	public static String meritsslide = "http://cysj.coolmoban.com/Friends/merits/act/meritsslide";// 功德簿信息
	public static String meritsdel = "http://cysj.coolmoban.com/Friends/merits/act/meritsdel";// 家庭禅修删除
	public static String StringsaveData = "http://cysj.coolmoban.com/Register/members/act/mempersonalmainpost";// 保存资料
	public static String StringSearch = "http://cysj.coolmoban.com/Register/members/act/mempersonalschool";// 搜索
	public static String chanting = "http://cysj.coolmoban.com/Friends/merits/act/chanting";// 家庭禅修上香诵经
	public static String origadd = "http://cysj.coolmoban.com/Originality/originality/act/origadd";// 创意发布
	public static String memattention = "http://cysj.coolmoban.com/Friends/members/act/memattention";// 会员关注的人
	public static String StringEditimage = "http://cysj.coolmoban.com/Register/members/act/mempersonalimage";// 编辑头像
	public static String Stringyanzheng = "http://cysj.coolmoban.com/Register/members/act/mempersonaltj";// 验证学校和政企
	public static String memfriends = "http://cysj.coolmoban.com/Friends/members/act/memfriends";// 创友录好友
	public static String StringAboutUs = "http://cysj.coolmoban.com/Article/about";// 关于我们
	public static String StringIndexRules = "http://cysj.coolmoban.com/Article/merits";// 指数规则
	public static String StringIndexRulechange = "http://cysj.coolmoban.com/Register/members/act/memccb";// 指数变化
	public static String StringIndexRulesHittory = "http://cysj.coolmoban.com/Register/memlist/act/indexlist";// 指数历史
	public static String StringIndexRulesHittorys = "http://cysj.coolmoban.com/Register/memlist/act/indexlistpage";// 指数历史分页
	public static String StringMychuangchuang = "http://cysj.coolmoban.com/Register/memlist/act/moneylist";// 我的创创币
	public static String StringMychuangchuangs = "http://cysj.coolmoban.com/Register/memlist/act/moneylistpage";// 我的创创币分页
	public static String memfans = "http://cysj.coolmoban.com/Friends/members/act/memfans";// 关注的粉丝
	public static String StringUP = "http://cysj.coolmoban.com/Originality/originality/act/origaddimg";// 上传图片和视频
	public static String Stringchuangyishow = "http://cysj.coolmoban.com/Originality/originality/act/origalist";// 创意列表
	public static String Stringchuangyishows = "http://cysj.coolmoban.com/Originality/originality/act/origalistpage";// 创意列表分页
	public static String origsinger = "http://cysj.coolmoban.com/Originality/originality/act/origsinger";// 创意作品—详情页
	public static String Stringchoose = "http://cysj.coolmoban.com/Common/commons/act/cityone";// 选择地区的时候国际初始化
	public static String Stringchooses = "http://cysj.coolmoban.com/Common/commons/act/cityajax";// 选择地区的时候具体选择
	public static String reportadd = "http://cysj.coolmoban.com/Originality/report/act/reportadd";// 创意作品—举报内容
	public static String reportlcass = "http://cysj.coolmoban.com/Originality/report/act/reportlcass";// 创意作品-举报类型
	public static String StringchuangyiMy = "http://cysj.coolmoban.com/register/dtlist/act/indexcylist";// 资料里面的创意列表
	public static String StringchuangyiMys = "http://cysj.coolmoban.com/register/dtlist/act/indexcylistpage";// 资料里面的创意列表分页
	public static String Stringshoucang = "http://cysj.coolmoban.com/Originality/praise/act/collection";// 收藏
	public static String Stringzan = "http://cysj.coolmoban.com/Originality/praise/act/praiseadd";// 赞
	public static String praisedel = "http://cysj.coolmoban.com/Originality/praise/act/praisedel";// 删除点赞
	public static String origdel = "http://cysj.coolmoban.com/Originality/originality/act/origdel";// 详情删除
	public static String StringOtherDetails = "http://cysj.coolmoban.com/register/dtlist/act/othermem";// 他人资料
	public static String StringChuangFriend = "http://cysj.coolmoban.com/Dynamic/dong/act/dtlist";// 创友圈
	public static String StringChuangFriends = "http://cysj.coolmoban.com/Dynamic/dong/act/dtlistpage";// 创友圈
	public static String stringdynamic = "http://cysj.coolmoban.com/Register/dtlist/act/indexdtlist";// 个人主页动态
	public static String stringdynamics = "http://cysj.coolmoban.com/Register/dtlist/act/indexdtlistpage";// 个人主页动态
	public static String origacommentadd = "http://cysj.coolmoban.com/Originality/comments/act/origacommentadd";// 创意评论提交
	public static String origacommentdel = "http://cysj.coolmoban.com/Originality/comments/act/origacommentdel";// 评论删除
	public static String dtadd = "http://cysj.coolmoban.com/Dynamic/dong/act/dtadd";// 创友圈发布动态
	public static String stringLook = "http://cysj.coolmoban.com/Register/dtlist/act/guanz";// 关注
	public static String stringNoLook = "http://cysj.coolmoban.com/Register/dtlist/act/qxguanz";// 取消关注
	public static String memsc = "http://cysj.coolmoban.com/Register/memlist/act/memsc";// 个人主页收藏列表
	public static String memscs = "http://cysj.coolmoban.com/Register/memlist/act/memscpage";// 个人主页收藏列表
	public static String memscdelete = "http://cysj.coolmoban.com/Register/memlist/act/memscdel";// 个人主页删除
	public static String lines = "http://cysj.coolmoban.com/Contest/linelist/act/lines";// 创意世界线下报名
	public static String linespage = "http://cysj.coolmoban.com/Contest/linelist/act/linespage";// 创意世界线下报名分页
	public static String linesinger = "http://cysj.coolmoban.com/Contest/linelist/act/linesinger";// 创意世界大赛线下比赛详情
	public static String register = "http://cysj.coolmoban.com/Contest/linelist/act/register";// 创意世界大赛线下比赛详情注册
	public static String Stringcheckgame = "http://cysj.coolmoban.com/Contest/linelist/act/payrecord";// 报名比赛
	public static String registers = "http://cysj.coolmoban.com/Contest/linelist/act/registers";// 创意世界大赛线下比赛详情注册
	public static String badd = "http://cysj.coolmoban.com/Bit/bitlist/act/badd";// 创意世界大赛发布
	public static String blist = "http://cysj.coolmoban.com/Bit/bitlist/act/blist";// 创意世界大赛列表
	public static String blistpage = "http://cysj.coolmoban.com/Bit/bitlist/act/blistpage";// 创意世界大赛列表分页
	public static String bsinger = "http://cysj.coolmoban.com/Bit/bitlist/act/bsinger";// 创意世界大赛列表详情
	public static String gzbit = "http://cysj.coolmoban.com/Bit/bitlist/act/gzbit";// 创意世界大赛-关注大赛
	public static String invmem = "http://cysj.coolmoban.com/Bit/bitlist/act/invmem";// 热门创意比赛-邀请成员
	public static String Stringruchuangjuan = "http://cysj.coolmoban.com/Register/memlist/act/ticket";// 入场卷
	public static String Stringruchuangjuans = "http://cysj.coolmoban.com/Register/memlist/act/ticketpage";// 入场卷分页
	public static String StringLookGame = "http://cysj.coolmoban.com/Friends/members/act/membit";// 关注比赛
	public static String StringLookGames = "http://cysj.coolmoban.com/Friends/members/act/membitpage";// 关注比赛分页
	public static String worklist = "http://cysj.coolmoban.com/Bit/matchform/act/worklist";// 创意世界大赛作品列表
	public static String worklistpage = "http://cysj.coolmoban.com/Bit/matchform/act/worklistpage";// 创意世界大赛作品列表分页
	public static String workadd = "http://cysj.coolmoban.com/Bit/matchform/act/workadd";// 创意世界大赛作品提交
	public static String uploadfile = "http://cysj.coolmoban.com/Bit/bitlist/act/uploadfile";// 创意世界大赛作品提交多图或者视频
	public static String zanadd = "http://cysj.coolmoban.com/Bit/others/act/zhicb";// 创意世界大赛作品竞猜
	public static String winccb = "http://cysj.coolmoban.com/Bit/others/act/winccb";//创意世界大赛作品获胜
	public static String Stringguanzhu = "http://cysj.coolmoban.com/Bit/bitlist/act/memlist";// 关注成员列表
	public static String Stringguanzhusearch = "http://cysj.coolmoban.com/Bit/bitlist/act/memlistcha";// 关注成员列表搜索
	public static String worksinger = "http://cysj.coolmoban.com/Bit/matchform/act/worksinger";// 创意作品—详情页
	public static String Stringjumpzhikurenzhen = "http://cysj.coolmoban.com/Register/memset/act/think";// 智库认证
	public static String Stringzhikurenzhen = "http://cysj.coolmoban.com/Register/memset/act/thinkpost";// 智库认证
	public static String Stringzhikuzhuanjiachushihua = "http://cysj.coolmoban.com/Register/memset/act/bankclas";// 智库专家初始化
	public static String qxbit = "http://cysj.coolmoban.com/Bit/bitlist/act/qxbit";//取消关注比赛
	public static String StringchuangyouquanRanking = "http://cysj.coolmoban.com/Charts/chart/act/friends";//创友圈排行
	public static String StringchuangyouquanRankings = "http://cysj.coolmoban.com/Charts/chart/act/friendslist";//创友圈排行 分页
	public static String invmempost = "http://cysj.coolmoban.com/Bit/bitlist/act/invmempost";//邀请成员专家
	public static String StringzhishuRankingSchool = "http://cysj.coolmoban.com/Charts/chart/act/school";//创意指数学校排行
	public static String StringzhishuRankingSchools = "http://cysj.coolmoban.com/Charts/chart/act/schoollist";//创意指数学校排行
	public static String StringzhishuRankingdiqu = "http://cysj.coolmoban.com/Charts/chart/act/country";//创意指数地区排行
	public static String StringzhishuRankingdiqus = "http://cysj.coolmoban.com/Charts/chart/act/countrylist";//创意指数地区排行分页
	public static String bitset = "http://cysj.coolmoban.com/Bit/bitlist/act/bitset";//返回的消息提醒
	public static String bitsetpost = "http://cysj.coolmoban.com/Bit/bitlist/act/bitsetpost";//消息提醒开关
	public static String thlist = "http://cysj.coolmoban.com/Think/thinks/act/thlist";//热门智库列表
	public static String thlistpage = "http://cysj.coolmoban.com/Think/thinks/act/thlistpage";//热门智库列表分页
	public static String StringareaRankingchuangyi = "http://cysj.coolmoban.com/Charts/chart/act/chuang";//创意指数排行-地区排行-创意
	public static String StringareaRankingchuangyis = "http://cysj.coolmoban.com/Charts/chart/act/chuanglist";//创意指数排行-地区排行-创意
	public static String memlist= "http://cysj.coolmoban.com/Charts/chart/act/memlist";//创意指数排行-地区排行-用户列表
	public static String thapply = "http://cysj.coolmoban.com/Think/thinks/act/thapply";//热门智库列表申请提交
	public static String ladd = "http://cysj.coolmoban.com/Excellent/lent/act/ladd";//优秀遗产提交
	public static String llist = "http://cysj.coolmoban.com/Excellent/lent/act/llist";//优秀遗产列表
	public static String ltoup = "http://cysj.coolmoban.com/Excellent/lent/act/ltoup";//优秀遗产投票
	public static String llistpage = "http://cysj.coolmoban.com/Excellent/lent/act/llistpage";//优秀遗产列表 分页
	public static String lsinger = "http://cysj.coolmoban.com/Excellent/lent/act/lsinger";//优秀遗产详情查看
	public static String thsinger = "http://cysj.coolmoban.com/Think/thinks/act/thsinger";//创意世界智库详情界面
	public static String yxcguo = "http://cysj.coolmoban.com/Think/thinks/act/yxcguo";//创意世界优秀成果
	public static String index = "http://cysj.coolmoban.com/Indexs/index/act/index";//首页
	public static String news = "http://cysj.coolmoban.com/Indexs/index/act/news";//新闻
	public static String newslist = "http://cysj.coolmoban.com/Indexs/index/act/newslist";//新闻分页
	public static String liu = "http://cysj.coolmoban.com/Article/liu";//意见反馈
	public static String messagedel = "http://cysj.coolmoban.com/Indexs/index/act/messagedel";//系统消息删除
	public static String messagelist = "http://cysj.coolmoban.com/Indexs/index/act/messagelist";//系统消息
	public static String messagelistpage = "http://cysj.coolmoban.com/Indexs/index/act/messagelistpage";//系统消息分页
	public static String myidea = "http://cysj.coolmoban.com/Indexs/index/act/myidea";//我的智库
	public static String thlists = "http://cysj.coolmoban.com/Think/thinksinger/act/thlist";//创意世界智库成员
	public static String thlistss = "http://cysj.coolmoban.com/Think/thinksinger/act/thlists";//创意世界智库成员搜索
	public static String thzulist = "http://cysj.coolmoban.com/Think/thinksinger/act/thzulist";//智库组列表
	public static String thzudel = "http://cysj.coolmoban.com/Think/thinksinger/act/thzudel";//智库组删除
	public static String thzuadd = "http://cysj.coolmoban.com/Think/thinksinger/act/thzuadd";//智库添加
	public static String singer = "http://cysj.coolmoban.com/Search/sch/act/singer";//创创召搜索列表
	public static String bankcla = "http://cysj.coolmoban.com/Register/memset/act/bankcla";//智库成员类型表筛选
	public static String newspage = "http://cysj.coolmoban.com/Search/page/act/newspage";//创创召搜索列表(新闻分页)
	public static String zhipage = "http://cysj.coolmoban.com/Search/page/act/zhipage";//创创召搜索列表(智库专家)
	public static String chuangpage = "http://cysj.coolmoban.com/Search/page/act/chuangpage";//创创召搜索列表(创意世界
	public static String youpage = "http://cysj.coolmoban.com/Search/page/act/youpage";//创创召搜索列表(创友圈)
	public static String repage = "http://cysj.coolmoban.com/Search/page/act/repage";//创创召搜索列表(热门比赛)
	public static String xiapage = "http://cysj.coolmoban.com/Search/page/act/xiapage";//创创召搜索列表(线下大赛)
	public static String zhuanjia = "http://cysj.coolmoban.com/Charts/chart/act/zhuanjia";//创意指数排行-地区排行-智库专家列表
	public static String zhuanjiapage = "http://cysj.coolmoban.com/Charts/chart/act/zhuanjiapage";//创意指数排行-地区排行-智库专家列表分页
}
